name: Ascii Artwork Print

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Github Checkout Action
          uses: actions/checkout@v4

        - name: Running ascii script
          run: |
             chmod +x script.sh
             ./script.sh