name: Devsecops-CI/CD-Docker
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    

jobs:
    build-and-run:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code in Repo
            uses: actions/checkout@v4
          - name: Build Docker Image
            run: |
              docker build -t flask-app .
          - name: Run Docker Container
            run: |
              docker run -d -p 5000:5000 --name flask-container flask-app

          - name: Verify if container is running
            run: |
              docker ps -a