name: My Github Actions

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Github Checkout Action
          uses: actions/checkout@v4

        - name: Welcome message
          run: echo "My First Github Action mssg"

        - name: List Files
          run: ls ..

        - name: Readme Read
          run: cat README.md

        - name: Read Code
          run: cat app.py